//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaShareBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediaShareBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4Head
        ///Anon
        ///BitBoss
        ///Charity
        ///Cheer
        ///DansGame
        ///DoodleCheer
        ///EleGiggle
        ///FailFish
        ///FrankerZ
        ///Goal
        ///HeyGuys
        ///HolidayCheer
        ///Kappa
        ///Kreygasm
        ///MrDestructoid
        ///Muxy
        ///NotLikeThis
        ///PJSalt
        ///Party
        ///PogChamp
        ///Pride
        ///RIPCheer
        ///Scoops
        ///SeemsGood
        ///Shamrock
        ///ShowLove
        ///Streamlabs
        ///SwiftRage
        ///TriHard
        ///VoHiYo
        ///bday
        ///uni.
        /// </summary>
        internal static string Cheermotes {
            get {
                return ResourceManager.GetString("Cheermotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Version 2019080501, Last Updated Mon Aug  5 07:07:01 2019 UTC
        ///AAA
        ///AARP
        ///ABARTH
        ///ABB
        ///ABBOTT
        ///ABBVIE
        ///ABC
        ///ABLE
        ///ABOGADO
        ///ABUDHABI
        ///AC
        ///ACADEMY
        ///ACCENTURE
        ///ACCOUNTANT
        ///ACCOUNTANTS
        ///ACO
        ///ACTOR
        ///AD
        ///ADAC
        ///ADS
        ///ADULT
        ///AE
        ///AEG
        ///AERO
        ///AETNA
        ///AF
        ///AFAMILYCOMPANY
        ///AFL
        ///AFRICA
        ///AG
        ///AGAKHAN
        ///AGENCY
        ///AI
        ///AIG
        ///AIGO
        ///AIRBUS
        ///AIRFORCE
        ///AIRTEL
        ///AKDN
        ///AL
        ///ALFAROMEO
        ///ALIBABA
        ///ALIPAY
        ///ALLFINANZ
        ///ALLSTATE
        ///ALLY
        ///ALSACE
        ///ALSTOM
        ///AM
        ///AMERICANEXPRESS
        ///AMERICANFAMILY
        ///AMEX
        ///AMFAM
        ///AMICA
        ///AMSTERDAM
        ///ANALYTICS
        ///ANDROID
        ///ANQUAN
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TLDs {
            get {
                return ResourceManager.GetString("TLDs", resourceCulture);
            }
        }
    }
}
